#version 460
// The MIT License (MIT)
//
// Copyright (c) 2026 Xiaoyang Chen
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
// BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#extension GL_GOOGLE_include_directive : require
// C = A, element by element, each side with strides of its own and A's elements converted to C's
// type. What copy, contiguous and cast all are. Between two integer types the element is moved
// as an integer, so a long is not squeezed through a float on its way.
#include "common.glsl"

layout(local_size_x = 256) in;

layout(push_constant) uniform Push {
  uint64_t c;
  uint64_t a;
  uint numel;
  uint ndim;
  uint shape[MAX_DIMS];
  uint strideA[MAX_DIMS];
  uint strideC[MAX_DIMS];
} pc;

void main() {
  uint i = globalIndex();
  if (i >= pc.numel) return;

  uint offsetA = 0;
  uint offsetC = 0;
  uint rest = i;
  for (int d = int(pc.ndim) - 1; d >= 0; --d) {
    uint size = pc.shape[d];
    uint next = rest / size;
    uint index = rest - next * size;
    offsetA += index * pc.strideA[d];
    offsetC += index * pc.strideC[d];
    rest = next;
  }

#if defined(A_INTEGER) && defined(C_INTEGER) && !defined(C_BOOL) && !defined(A_BOOL)
  BufferC(pc.c).v[offsetC] = C_T(int64_t(LOAD_A_RAW(pc.a, offsetA)));
#elif defined(A_BOOL) && defined(C_BOOL)
  STORE_C_RAW(pc.c, offsetC, LOAD_A_RAW(pc.a, offsetA));
#else
  STORE_C(pc.c, offsetC, LOAD_A(pc.a, offsetA));
#endif
}
