// The reference constants below are machine-written by `tools/campplus_reference.py` at f32's
// own precision. Trimming each to the shortest decimal that round-trips would make the file
// disagree with what the generator prints, which is the one property worth keeping.
#![allow(clippy::excessive_precision)]

//! CAMPPlus against CAMPPlus: this runtime's speaker encoder beside 3D-Speaker's own.
//!
//! The constants below come from `tools/campplus_reference.py`, which downloads the reference
//! implementation and runs it. They are not a second opinion written from the same paper -- such
//! a thing would agree with a bug as readily as with the model -- they are what the model this
//! one is a port of actually produced.
//!
//! No package and no download. Every parameter is filled from its own name, by the same hash and
//! the same sine in both languages, so the two sides need no file between them and cannot
//! disagree about the order they walk the model in. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/campplus_reference.py
//! ```
//!
//! The model is small -- 16 bands, 16 initial channels, an 8-dimensional embedding -- but every
//! *count* is the release's: three dense blocks, twelve then twenty-four then sixteen layers
//! deep. Depth is what a dense block's bookkeeping gets wrong, since each layer concatenates onto
//! the channels of all the ones before it, and 420 frames is what gives the segment pooling
//! inside `CAMLayer` three segments with a short one at the end.

use waifu::indextts::campplus::{self, Config};
use waifu::flint::{Device, Graph, Ir, ParamSource, RunContext, Tensor};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

// The reference's configuration, which `tools/campplus_reference.py` states in the same numbers.
const FEAT_DIM: i32 = 16;
const EMBEDDING_SIZE: i32 = 8;
const GROWTH_RATE: i32 = 4;
const BN_SIZE: i32 = 2;
const INIT_CHANNELS: i32 = 16;
const FRAMES: i32 = 420;

const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.8;

// Generated by tools/campplus_reference.py -- 420 frames, 16 bands.

/// `input_mean`, (1, 16) -- 16 of 16, all.
const INPUT_MEAN: [f32; 16] = [
    3.759403e-03,
    4.396765e-03,
    2.751513e-03,
    -3.222108e-04,
    -3.228656e-03,
    -4.458919e-03,
    -3.374298e-03,
    -5.378803e-04,
    2.577780e-03,
    4.355166e-03,
    3.871529e-03,
    1.377959e-03,
    -1.830991e-03,
    -4.089368e-03,
    -4.224715e-03,
    -2.166767e-03,
];

/// `head`, (1, 64, 420) -- 8 of 26880, at [0, 3367, 6734, 10101, 13468, 16835, 20202, 23569].
const HEAD: [f32; 8] = [
    0.000000e+00,
    0.000000e+00,
    5.587083e-01,
    2.479511e-01,
    5.094240e-01,
    6.855104e-02,
    0.000000e+00,
    0.000000e+00,
];

/// `embedding`, (1, 8) -- 8 of 8, all.
const EMBEDDING: [f32; 8] = [
    1.830624e-02,
    2.886495e-01,
    7.330610e-01,
    9.862975e-01,
    8.964829e-01,
    7.650215e-01,
    8.754505e-01,
    7.962046e-01,
];

fn config() -> Config {
    Config {
        feat_dim: FEAT_DIM,
        embedding_size: EMBEDDING_SIZE,
        growth_rate: GROWTH_RATE,
        bn_size: BN_SIZE,
        init_channels: INIT_CHANNELS,
    }
}

/// FNV-1a over a parameter's name. The Python side computes the same thing the same way.
fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

/// `count` numbers that belong to this parameter and no other.
///
/// The arithmetic is float64 in both languages and rounded once, at the end, so the two fills are
/// equal bit for bit rather than close.
fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

/// Every weight, made up from its own name at the moment the graph asks for it.
///
/// Asking the graph rather than keeping a list is the point: there is no second description of
/// the model here that could fall out of step with the first. A weight the graph does not ask
/// for is never made, and one it asks for under the wrong name is filled with the wrong numbers
/// and fails loudly rather than being quietly missing.
struct Filled;

impl ParamSource for Filled {
    fn load(&self, name: &str, shape: &[i32]) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        // The two halves of a folded normalization are filled the way the reference sets them:
        // a scale that cannot be zero, and a smaller shift. See `tools/campplus_reference.py`.
        let values = if let Some(stem) = name.strip_suffix(".scale") {
            fill(&format!("{stem}.scale"), count, 0.5)
                .into_iter()
                .map(|value| value.abs() + 0.5)
                .collect()
        } else if name.ends_with(".shift") {
            fill(name, count, 0.3)
        } else {
            fill(name, count, WEIGHT_SCALE)
        };

        Ok(Tensor::from_f32(shape, &values)?)
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    /// Everything the graph asks for exists, because it is made when it is asked for.
    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

/// The filterbank energies the reference was handed: filled from a name, then centred over time
/// the way `infer_v2_5.py` centres real ones.
fn input() -> Tensor {
    let raw = fill("input", (FRAMES * FEAT_DIM) as usize, INPUT_SCALE);

    let centred: Vec<f32> = raw
        .iter()
        .enumerate()
        .map(|(index, value)| value - INPUT_MEAN[index % FEAT_DIM as usize])
        .collect();

    Tensor::from_f32(&[1, FRAMES, FEAT_DIM], &centred).unwrap()
}

/// Where the reference sampled a probe: an odd stride, so it walks channels and time together
/// rather than sitting in one channel where a ReLU may have left nothing.
fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn close(got: &[f32], want: &[f32], tolerance: f32, what: &str) {
    assert_eq!(got.len(), want.len(), "{what}: lengths differ");

    for (index, (a, b)) in got.iter().zip(want).enumerate() {
        assert!(
            (a - b).abs() <= tolerance * (1.0 + b.abs()),
            "{what} at {index}: {a} is not {b}"
        );
    }
}

fn run(build: impl FnOnce(&Graph) -> waifu::flint::Value) -> (Vec<i32>, Vec<f32>) {
    let g = Graph::new();
    let out = build(&g);
    g.output("out", out);

    let filled = Filled;
    let x = input();
    let ir = Ir::compile(&g);
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .input("x", &x),
        )
        .unwrap();

    let tensor = outputs[0].1.to_device(CPU).unwrap();

    (tensor.shape(), tensor.to_vec_f32().unwrap())
}

/// The 2-D front end on its own: the part that walks down the frequency axis.
///
/// Its own test because it is where the one thing `flint` could not express lives -- a stride
/// down frequency but not time -- and because a front end that is subtly wrong would otherwise
/// only show up as an embedding that is wrong for no visible reason.
#[test]
fn the_front_end_is_the_reference_front_end() {
    let config = config();

    let (shape, got) = run(|g| {
        let x = g.contiguous(g.transpose(g.input("x"), 1, 2));
        campplus::front_end(
            &g.subgraph("head"),
            x,
            &config,
            waifu::flint::Extent::At(FRAMES),
        )
    });

    assert_eq!(
        shape,
        vec![1, 32 * (FEAT_DIM / 8), FRAMES],
        "the front end folded frequency into the channels wrongly"
    );

    let indices = probe_indices(got.len(), HEAD.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();
    close(&sampled, &HEAD, 1e-4, "front end");
}

/// The whole encoder, end to end.
#[test]
fn the_embedding_is_the_reference_embedding() {
    let config = config();

    let (shape, got) =
        run(|g| campplus::graph(g, g.input("x"), &config, FRAMES, F32, CPU).unwrap());

    assert_eq!(shape, vec![1, EMBEDDING_SIZE]);
    close(&got, &EMBEDDING, 1e-4, "embedding");
}

/// The graph asks for exactly the weights the exporter writes, and no others.
///
/// A numeric test does catch a missing layer -- the embedding moves -- but it says only that
/// something is wrong. This says what: `tools/campplus_exporter.py` produces 573 tensors for this
/// architecture, one per convolution weight, convolution bias and folded normalization, and a
/// graph that asks for a different number has skipped something or asked twice.
///
/// The names checked by hand are the far corners: the last layer of the deepest block, which a
/// loop that stops one short never reaches, and the shortcut that only the shape-changing
/// residual blocks have.
#[test]
fn the_graph_asks_for_exactly_the_weights_the_exporter_writes() {
    let config = config();

    let g = Graph::new();
    let out = campplus::graph(&g, g.input("x"), &config, FRAMES, F32, CPU).unwrap();
    g.output("out", out);

    let mut names = g.parameters();
    names.sort();

    let unique = names.len();
    names.dedup();
    assert_eq!(unique, names.len(), "the graph asks for a weight twice");

    assert_eq!(
        names.len(),
        573,
        "the exporter writes 573 tensors for this architecture"
    );

    for corner in [
        "head.conv1.weight",
        "head.layer2.0.shortcut.1.shift",
        "xvector.block3.tdnnd16.cam_layer.linear2.bias",
        "xvector.transit3.linear.weight",
        "xvector.dense.nonlinear.batchnorm.scale",
    ] {
        assert!(
            names.iter().any(|name| name == corner),
            "the graph never asks for {corner}"
        );
    }
}
