// The reference constants below are machine-written by `tools/indextts_emotion_reference.py` at
// f32's own precision.
#![allow(clippy::excessive_precision)]

//! IndexTTS-2.5's emotion path against the released source's own conformer and perceiver.
//!
//! No download and no checkpoint: `ConformerEncoder` and `PerceiverResampler` are imported from
//! the tree cached under `~/.cache/libwaifu/indextts-src` and run. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/indextts_emotion_reference.py
//! ```
//!
//! Why the reference is upstream's code rather than a second reading of the paper: a WeNet
//! conformer has several places where a reimplementation can be self-consistently wrong and still
//! produce a tensor of the right shape -- whether `rel_shift` is applied, which half of a gated
//! unit is the gate, whether the feed forward is halved for macaron style, whether the position
//! table is added to the input or only to the scores. None of those is visible in a shape, and
//! none would be caught by comparing this against a description of what it should do.
//!
//! # The weights scatter, and that is the point
//!
//! Every other reference here sweeps a sine per parameter. This draws by xorshift instead,
//! because most of what this module does is attention: a swept parameter makes every key in a
//! projection point nearly the same way, the softmax over them comes out flat, and a flat softmax
//! is an average -- which does not care what order its keys arrived in. `docs/indextts_gpt.md`
//! has the longer version, and the bug it cost.
//!
//! # Four probes and a table
//!
//! `positions` is the sinusoid table, which nothing learned and both sides build for themselves
//! -- so a disagreement there is the formula, before any weight is involved. The other four cut
//! the model where upstream itself cuts it: after `self.embed`, after the blocks, after the
//! perceiver, and after the two projections. A failure says which.
//!
//! # Verified by mutation, and the scale is why
//!
//! Nine plausible bugs were written into the module one at a time, and every one of them fails
//! here by between 55 and 11,000 times the tolerance: the gate taken from the wrong half of
//! either gated unit, the feed forward halved as though this conformer were macaron style (it is
//! not -- [`waifu::indextts::w2v_bert`]'s is, which is exactly how that mistake would arrive), the position
//! term dropped from the scores, `pos_bias_v` used where `pos_bias_u` belongs, the depthwise
//! convolution made causal, `norm_conv` and `norm_ff` swapped, `xscale` left off, and the
//! perceiver's latents left out of what they read.
//!
//! **The weight scale had to be raised to get there.** At the 0.25 the other reference scripts
//! here use, activations land where GELU is still nearly a straight line, `gelu(a) * b` and
//! `gelu(b) * a` come out within a thousandth of each other, and the end-to-end probe did not
//! notice the halves being swapped at all. Drawing at 0.7 puts the activations at the order of
//! one, which is where the released model runs and where its nonlinearities are nonlinear.
//!
//! One thing that is *not* a bug, and looked like one: concatenating the context the other way
//! round, `cat(context, latents)`, changes nothing. It permutes the keys and the values together
//! and a softmax does not care -- which holds only because there is no mask and no position
//! encoding in the perceiver's attention. Upstream's `emo_cond_mask_pad` prepends the latent's
//! own `True` at position zero, so the order would matter the moment a batch were padded.

use waifu::flint::{Device, Graph, Ir, ParamSource, RunContext, Tensor, Value};
use waifu::indextts::emotion::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

// The cut widths, which tools/indextts_emotion_reference.py states identically.
const INPUT_DIM: i32 = 24;
const ENCODER_DIM: i32 = 16;
const ENCODER_HEADS: i32 = 4;
const ENCODER_UNITS: i32 = 32;
const ENCODER_BLOCKS: i32 = 2;
const CNN_KERNEL: i32 = 7;
const LATENT_DIM: i32 = 20;
const LATENTS: i32 = 1;
const PERCEIVER_DEPTH: i32 = 2;
const PERCEIVER_HEADS: i32 = 4;
const PERCEIVER_HEAD_DIM: i32 = 8;
const PERCEIVER_MULT: f32 = 2.0;
const MODEL_DIM: i32 = 24;
const FRAMES: i32 = 21;

const WEIGHT_SCALE: f64 = 0.7;
const INPUT_SCALE: f64 = 1.0;

/// What PyTorch and this agree to within. The house figure for a comparison against torch, which
/// is wider than the 1e-5 an invariant inside this crate is held to.
const TOLERANCE: f32 = 2e-3;

// Generated by tools/indextts_emotion_reference.py -- 21 frames, 2 blocks.

/// `positions`, (1, 10, 16) -- the sinusoid table, which nothing learned
///   8 of 160, at [0, 27, 54, 81, 108, 135, 2, 29].
const POSITIONS: [f32; 8] = [
    0.000000e+00,
    9.999950e-01,
    9.472609e-02,
    2.836622e-01,
    5.999964e-03,
    9.681703e-01,
    0.000000e+00,
    9.999995e-01,
];

/// `embedded`, (1, 10, 16) -- subsampled, flattened, projected and scaled
///   8 of 160, at [0, 27, 54, 81, 108, 135, 2, 29].
const EMBEDDED: [f32; 8] = [
    -3.016549e+01,
    8.164203e+00,
    -7.890924e+00,
    -1.590777e+00,
    5.303902e+00,
    -3.962871e+00,
    -7.975721e+00,
    1.108405e+01,
];

/// `encoded`, (1, 10, 16) -- all of the conformer
///   8 of 160, at [0, 27, 54, 81, 108, 135, 2, 29].
const ENCODED: [f32; 8] = [
    -8.931468e-01,
    -4.766875e-01,
    3.816855e-01,
    8.819730e-01,
    -1.295833e-01,
    -5.904130e-01,
    5.838200e-01,
    -5.697700e-01,
];

/// `resampled`, (1, 1, 20) -- one latent, having read the whole recording
///   8 of 20, at [0, 9, 18, 7, 16, 5, 14, 3].
const RESAMPLED: [f32; 8] = [
    3.904039e-02,
    -2.801999e-01,
    8.310743e-02,
    -2.465614e-01,
    -1.622303e-01,
    -1.070007e+00,
    1.292868e-01,
    -7.545123e-03,
];

/// `emotion`, (1, 24) -- the row the GPT is handed
///   8 of 24, at [0, 10, 20, 6, 16, 2, 12, 22].
const EMOTION: [f32; 8] = [
    -1.222435e+00,
    2.625168e+00,
    1.744938e+00,
    -8.406451e-01,
    2.426764e-01,
    -3.490649e+00,
    -1.119711e+00,
    -3.457034e+00,
];

fn config() -> Config {
    Config {
        input_dim: INPUT_DIM,
        encoder_dim: ENCODER_DIM,
        encoder_heads: ENCODER_HEADS,
        encoder_units: ENCODER_UNITS,
        encoder_blocks: ENCODER_BLOCKS,
        cnn_kernel: CNN_KERNEL,
        latent_dim: LATENT_DIM,
        latents: LATENTS,
        perceiver_depth: PERCEIVER_DEPTH,
        perceiver_heads: PERCEIVER_HEADS,
        perceiver_head_dim: PERCEIVER_HEAD_DIM,
        perceiver_mult: PERCEIVER_MULT,
        model_dim: MODEL_DIM,
        layer_norm_eps: 1e-5,
    }
}

fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

/// `count` numbers in `[-scale, scale]`, drawn by xorshift from `name`.
///
/// Scattered rather than swept: see the note at the top of this file.
fn scatter(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let mut state = hash32(name) | 1;

    (0..count)
        .map(|_| {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;

            ((f64::from(state) / f64::from(u32::MAX) * 2.0 - 1.0) * scale) as f32
        })
        .collect()
}

struct Scattered;

impl ParamSource for Scattered {
    fn load(&self, name: &str, shape: &[i32]) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(
            shape,
            &scatter(name, count, WEIGHT_SCALE),
        )?)
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn probe(tensor: &Tensor) -> (Vec<i32>, Vec<f32>) {
    let values = tensor.to_vec_f32().unwrap();
    let indices = probe_indices(values.len(), 8);

    (
        tensor.shape(),
        indices.iter().map(|index| values[*index]).collect(),
    )
}

fn close(got: &[f32], want: &[f32], what: &str) {
    for (index, (left, right)) in got.iter().zip(want).enumerate() {
        assert!(
            (left - right).abs() <= TOLERANCE,
            "{what}[{index}]: {left} against {right}",
        );
    }
}

fn features() -> Tensor {
    Tensor::from_f32(
        &[1, FRAMES, INPUT_DIM],
        &scatter("features", (FRAMES * INPUT_DIM) as usize, INPUT_SCALE),
    )
    .unwrap()
}

/// Build a graph around `stage`, run it over the same recording, and sample what comes out.
///
/// The position table is an input rather than a constant, the way the model takes it, so every
/// probe below reads the one [`emotion::positional_encoding`] built -- which is itself
/// the first thing checked.
/// Where the conformer's weights live, which is where a probe of one stage has to look for them.
///
/// The names a parameter source is handed are the checkpoint's whole names, and a stage run on
/// its own at the root would ask for `embed.conv.0.weight` where the reference drew
/// `emo_conditioning_encoder.embed.conv.0.weight`. Same shapes, different numbers, and every
/// probe below would fail for that reason rather than its own.
fn encoder_namespace(g: &Graph) -> Graph {
    g.subgraph("emo_conditioning_encoder")
}

fn perceiver_namespace(g: &Graph) -> Graph {
    g.subgraph("emo_perceiver_encoder")
}

fn run(stage: impl Fn(&Graph, Value, &Config, Value) -> Value) -> (Vec<i32>, Vec<f32>) {
    let config = config();
    let positions =
        emotion::positional_encoding(Config::subsampled(FRAMES), ENCODER_DIM, CPU)
            .unwrap();

    let g = Graph::new();
    let out = stage(&g, g.input("x"), &config, g.input("positions"));
    g.output("out", out);

    let weights = Scattered;
    let ir = Ir::compile(&g);
    let outputs = ir
        .run(
            &RunContext::new(&weights)
                .input("x", &features())
                .input("positions", &positions),
        )
        .unwrap();

    probe(&outputs[0].1.to_device(CPU).unwrap())
}

/// The table both sides build for themselves. A disagreement here is the formula, and every
/// probe after it would fail for a reason that is not its own.
#[test]
fn builds_the_sinusoid_table_upstream_carries() {
    let table = emotion::positional_encoding(Config::subsampled(FRAMES), ENCODER_DIM, CPU)
        .unwrap();

    let (shape, got) = probe(&table);

    assert_eq!(shape, vec![1, Config::subsampled(FRAMES), ENCODER_DIM]);
    close(&got, &POSITIONS, "positions");
}

/// `Conv2dSubsampling2` and the projection over what it flattens, times `xscale`.
///
/// Also the one place the subsampled length is asserted outright: a convolution at stride two
/// with no padding leaves `(T - 3) / 2 + 1` frames and not `T / 2`, and the two differ for every
/// length.
#[test]
fn embeds_the_recording_the_way_the_subsampling_does() {
    let (shape, got) = run(|g, x, config, _| {
        emotion::embed(&encoder_namespace(g).subgraph("embed"), x, config, FRAMES)
    });

    assert_eq!(shape, vec![1, 10, ENCODER_DIM]);
    assert_eq!(Config::subsampled(FRAMES), 10);
    close(&got, &EMBEDDED, "embedded");
}

/// The whole conformer: the blocks, their relative attention, and `after_norm`.
#[test]
fn reads_the_recording_the_way_the_conformer_does() {
    let (shape, got) = run(|g, x, config, positions| {
        emotion::encoder(
            &encoder_namespace(g),
            x,
            config,
            FRAMES,
            positions,
            F32,
            CPU,
        )
        .unwrap()
    });

    assert_eq!(shape, vec![1, 10, ENCODER_DIM]);
    close(&got, &ENCODED, "encoded");
}

/// The perceiver on its own, fed the conformer's output.
///
/// One latent in and one latent out, which is what makes the stage after it a vector rather than
/// a sequence.
#[test]
fn boils_the_recording_down_the_way_the_perceiver_does() {
    let (shape, got) = run(|g, x, config, positions| {
        let encoded = emotion::encoder(
            &encoder_namespace(g),
            x,
            config,
            FRAMES,
            positions,
            F32,
            CPU,
        )
        .unwrap();

        emotion::perceiver(
            &perceiver_namespace(g),
            encoded,
            config,
            Config::subsampled(FRAMES),
            F32,
            CPU,
        )
    });

    assert_eq!(shape, vec![1, LATENTS, LATENT_DIM]);
    close(&got, &RESAMPLED, "resampled");
}

/// All four stages, which is what `Gpt::prefill` is handed.
#[test]
fn produces_the_emotion_row_the_gpt_takes() {
    let (shape, got) = run(|g, x, config, positions| {
        emotion::graph(g, x, config, FRAMES, positions, F32, CPU).unwrap()
    });

    assert_eq!(shape, vec![1, MODEL_DIM]);
    close(&got, &EMOTION, "emotion");
}

/// The emotion row is the width the GPT's prefix wants, at the real configuration rather than
/// this file's cut one.
///
/// A shape rather than a number, and worth its own test: every probe above runs a model whose
/// widths were chosen to be quick, and the one thing they cannot check is that the released
/// widths fit together. `model_dim` here and `gpt::Config::indextts().model_dim` are two
/// constants that have to agree, and nothing else compares them.
#[test]
fn releases_a_row_as_wide_as_the_gpt_is() {
    let emotion = Config::indextts();
    let gpt = waifu::indextts::gpt::Config::indextts();

    assert_eq!(emotion.model_dim, gpt.model_dim);
    assert_eq!(emotion.input_dim, 1024);
    assert_eq!(emotion.latents, 1);
}
