// The reference constants below are machine-written by `tools/indextts_gpt_reference.py` at
// f32's own precision.
#![allow(clippy::excessive_precision)]

//! IndexTTS-2.5's GPT against GPT-2 itself, which is where the reference lives — no download, of
//! source or of weights, since `GPT2Model` is in the transformers this venv already pins.
//!
//! Every parameter is filled from its own name, by the same FNV-1a hash and the same sine in both
//! languages. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/indextts_gpt_reference.py
//! ```
//!
//! Every width is cut, and so is the layer count: a GPT-2 stack has no bookkeeping that turns on
//! its depth, so four layers exercise the same block that twenty-four do.
//!
//! Three probes, kept apart so a failure says which part: the stack, the head on top of it, and
//! the embeddings in front of it.

use waifu::flint::{Device, Graph, Ir, ParamSource, Residency, RunContext, Tensor, Value};
use waifu::indextts_gpt::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

const MODEL_DIM: i32 = 64;
const LAYERS: i32 = 4;
const HEADS: i32 = 4;
const NUMBER_MEL_CODES: i32 = 40;
const NUMBER_TEXT_TOKENS: i32 = 50;
const MAX_TEXT_TOKENS: i32 = 30;
const LENGTH: i32 = 12;

const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.6;

// Generated by tools/indextts_gpt_reference.py -- 12 positions, 4 layers.

/// `hidden`, (1, 12, 64) -- 8 of 768, at [0, 103, 206, 309, 412, 515, 618, 721].
const HIDDEN: [f32; 8] = [
    2.803829e-01,
    -3.729934e-01,
    -5.173998e-01,
    4.573033e-01,
    2.166724e-01,
    -2.190239e-02,
    1.495603e-01,
    1.700695e-01,
];

/// `scores`, (1, 12, 40) -- 8 of 480, at [0, 67, 134, 201, 268, 335, 402, 469].
const SCORES: [f32; 8] = [
    2.275380e+00,
    1.006527e+00,
    -3.114424e-01,
    -4.634286e-01,
    -6.176636e-01,
    -1.071727e+00,
    2.319274e+00,
    1.342803e+00,
];

/// `embedded`, (1, 12, 64) -- 8 of 768, at [0, 103, 206, 309, 412, 515, 618, 721].
const EMBEDDED: [f32; 8] = [
    -1.652834e-01,
    1.015142e-01,
    -1.307451e-01,
    -5.091574e-01,
    -3.910238e-01,
    -1.674240e-01,
    -2.829498e-01,
    -1.076710e-01,
];

fn config() -> Config {
    Config {
        model_dim: MODEL_DIM,
        layers: LAYERS,
        heads: HEADS,
        number_mel_codes: NUMBER_MEL_CODES,
        number_text_tokens: NUMBER_TEXT_TOKENS,
        max_mel_tokens: 200,
        max_text_tokens: MAX_TEXT_TOKENS,
        start_mel_token: 38,
        stop_mel_token: 39,
        start_text_token: 0,
        stop_text_token: 1,
        languages: 9,
        layer_norm_eps: 1e-5,
    }
}

fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

struct Filled;

impl ParamSource for Filled {
    fn read(&self, name: &str, shape: &[i32], _pinned: bool) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(shape, &fill(name, count, WEIGHT_SCALE))?)
    }

    /// Made on the host, which is where these tests run.
    fn device(&self) -> Device {
        CPU
    }

    /// Kept: a weight made out of its name costs nothing to keep and there is no package
    /// behind it to stream one out of.
    fn residency(&self) -> Residency {
        Residency::Device
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn embeddings() -> Tensor {
    Tensor::from_f32(
        &[1, LENGTH, MODEL_DIM],
        &fill("embeddings", (LENGTH * MODEL_DIM) as usize, INPUT_SCALE),
    )
    .unwrap()
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn close(got: &[f32], want: &[f32], what: &str) {
    for (index, (a, b)) in got.iter().zip(want).enumerate() {
        assert!(
            (a - b).abs() <= 2e-3 * (1.0 + b.abs()),
            "{what} at {index}: {a} is not {b}"
        );
    }
}

/// Build, run and sample a graph the way the reference sampled its own output.
fn run(
    build: impl FnOnce(&Graph) -> Value,
    inputs: &[(&str, &Tensor)],
    probe: usize,
) -> (Vec<i32>, Vec<f32>) {
    let g = Graph::new();
    let out = build(&g);
    g.output("out", out);

    let filled = Filled;
    let mut context = RunContext::new(&filled);
    for (name, tensor) in inputs {
        context = context.input(name, tensor);
    }

    let ir = Ir::compile(&g, Residency::Device);
    let preloaded = ir.load(&filled).unwrap();
    let outputs = ir.run(&context.preloaded(&preloaded)).unwrap();
    let tensor = outputs[0].1.to_device(CPU).unwrap();
    let values = tensor.to_vec_f32().unwrap();
    let indices = probe_indices(values.len(), probe);

    (
        tensor.shape(),
        indices.iter().map(|index| values[*index]).collect(),
    )
}

/// The transformer stack, against GPT-2's own.
///
/// The one thing this is really asking is whether the position embedding stayed out. GPT-2 adds
/// its own unless it is told not to, and this model replaces it with zeros because the positions
/// it uses were added before the stack. A stack that quietly put them back would be wrong in
/// every layer and would still return a tensor of the right shape.
#[test]
fn the_backbone_is_gpt2() {
    let x = embeddings();
    let config = config();

    let (shape, got) = run(
        |g| indextts_gpt::backbone(g, g.input("x"), &config, LENGTH, F32, CPU).unwrap(),
        &[("x", &x)],
        HIDDEN.len(),
    );

    assert_eq!(shape, vec![1, LENGTH, MODEL_DIM]);
    close(&got, &HIDDEN, "backbone");
}

/// And the head on top of it: normalize, then score every token of the codec's alphabet.
#[test]
fn the_head_scores_the_alphabet() {
    let x = embeddings();
    let config = config();

    let (shape, got) = run(
        |g| indextts_gpt::graph(g, g.input("x"), &config, LENGTH, F32, CPU).unwrap(),
        &[("x", &x)],
        SCORES.len(),
    );

    assert_eq!(shape, vec![1, LENGTH, NUMBER_MEL_CODES]);
    close(&got, &SCORES, "head");
}

/// The embeddings in front: a token, where it sits, and what language it is in.
#[test]
fn the_text_embeddings_add_all_three() {
    let config = config();

    let text: Vec<i64> = (0..LENGTH as i64)
        .map(|i| i % NUMBER_TEXT_TOKENS as i64)
        .collect();
    let text = Tensor::from_i64(&[1, LENGTH], &text).unwrap();

    let positions: Vec<i64> = (0..LENGTH as i64).collect();
    let positions = Tensor::from_i64(&[LENGTH], &positions).unwrap();

    let language = Tensor::from_i64(&[1], &[3]).unwrap();

    let (shape, got) = run(
        |g| {
            indextts_gpt::text_embeddings(
                g,
                g.input("text"),
                g.input("positions"),
                g.input("language"),
                &config,
            )
        },
        &[
            ("text", &text),
            ("positions", &positions),
            ("language", &language),
        ],
        EMBEDDED.len(),
    );

    assert_eq!(shape, vec![1, LENGTH, MODEL_DIM]);
    close(&got, &EMBEDDED, "text embeddings");
}
