// The reference constants below are machine-written by `tools/indextts_features_reference.py` at
// f32's own precision.
#![allow(clippy::excessive_precision)]

//! IndexTTS-2.5's audio front end against the feature extractor the release itself calls.
//!
//! No download and no checkpoint: `SeamlessM4TFeatureExtractor` is in the pinned transformers in
//! this venv, and it is what `infer_v2_5.py` runs over the reference recording. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/indextts_features_reference.py
//! ```
//!
//! # Why a front end deserves its own test
//!
//! Nothing downstream of this can tell you it is wrong. A filterbank that is off by one bin, a
//! window that is periodic where Kaldi's is not, a pre-emphasis applied before the mean is
//! removed rather than after -- each of those produces a feature of exactly the right shape,
//! full of plausible numbers, and the first thing that notices is a voice that sounds like
//! somebody else. There is no shape to check and no assertion further down that fires.
//!
//! So the comparison is against the extractor itself, sample for sample, at both of the two
//! normalizations the pipeline asks for.
//!
//! # What the numbers are of
//!
//! A half second of chirp from 80 Hz to 6 kHz. A sweep rather than noise because it puts
//! different energy in different bands at different times, so a band that is wrong is visible;
//! noise would make every band look alike.
//!
//! # Verified by mutation
//!
//! Six plausible front-end bugs were written into the module one at a time, and each fails here:
//! a periodic window (0.07 out), a plain Hann instead of Povey's `hann^0.85` (0.26), pre-emphasis
//! walked forwards so it reads what it just wrote (0.96), the frame mean removed after
//! pre-emphasis rather than before (6.0), the population deviation instead of the sample one
//! (0.03), and the triangles built in hertz rather than in mel (1.9). Against a tolerance of
//! 2e-3.
//!
//! One that is *not* a bug, and looked like one: swapping Kaldi's mel scale for HTK's changes
//! nothing. `2595 * log10(1 + f / 700)` and `1127 * ln(1 + f / 700)` are the same function --
//! `2595 / ln(10)` is 1127.01 -- and even that last digit cancels, because the scale is only ever
//! used to space the corners linearly between two of its own values and to place the bins between
//! them. A constant factor divides out of every slope. The two names are a difference in
//! spelling, not in filterbank.

use waifu::indextts_features::{self, Analysis};

const RATE: f64 = 16000.0;
const SECONDS: f64 = 0.5;
const SAMPLES: usize = 8000;

const BINS: usize = 80;

/// What torch and this agree to within. Wider than an exact comparison because the reference
/// promotes to `float64` for the transform and this does too, but the two arrive at the mel
/// energies by a different summation order.
const TOLERANCE: f32 = 2e-3;

// Generated by tools/indextts_features_reference.py -- 8000 samples at 16000.

/// `w2v_features`, (24, 160) -- standardized per band, then stacked in pairs
///   8 of 3840, at [0, 487, 974, 1461, 1948, 2435, 2922, 3409].
const W2V_FEATURES: [f32; 8] = [
    2.672312e+00,
    6.038071e-01,
    2.764502e-01,
    -2.605077e-01,
    -4.172381e-01,
    -5.457411e-01,
    -6.048961e-01,
    -6.079430e-01,
];

/// `campplus_features`, (48, 80) -- each band's mean over time removed
///   8 of 3840, at [0, 487, 974, 1461, 1948, 2435, 2922, 3409].
const CAMPPLUS_FEATURES: [f32; 8] = [
    7.034213e+00,
    -8.482418e-01,
    -1.506391e+00,
    -1.937367e+00,
    -2.178713e+00,
    -2.510678e+00,
    -2.789521e+00,
    -3.191409e+00,
];

/// The same sweep the reference builds, in the same order of operations.
fn chirp() -> Vec<f32> {
    let mut running = 0.0f64;

    (0..SAMPLES)
        .map(|index| {
            let time = index as f64 / RATE;
            running += 80.0 + (6000.0 - 80.0) * time / SECONDS;

            (0.1 * (2.0 * std::f64::consts::PI * running / RATE).sin()) as f32
        })
        .collect()
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn close(got: &[f32], want: &[f32], what: &str) {
    for (index, (left, right)) in got.iter().zip(want).enumerate() {
        assert!(
            (left - right).abs() <= TOLERANCE,
            "{what}[{index}]: {left} against {right}",
        );
    }
}

fn probe(values: &[f32], want: &[f32], what: &str) {
    let sampled: Vec<f32> = probe_indices(values.len(), 8)
        .iter()
        .map(|index| values[*index])
        .collect();

    close(&sampled, want, what);
}

/// The 160-wide features w2v-bert reads, against `SeamlessM4TFeatureExtractor`.
#[test]
fn reads_a_recording_the_way_the_extractor_does() {
    let (features, pairs) = indextts_features::w2v_bert(&chirp());

    assert_eq!(pairs, 24);
    assert_eq!(features.len(), 24 * 2 * BINS);
    probe(&features, &W2V_FEATURES, "w2v_features");
}

/// The 80-wide ones CAMPPlus reads, against the same analysis unscaled.
#[test]
fn reads_a_recording_the_way_kaldi_does() {
    let (features, frames) = indextts_features::campplus(&chirp());

    assert_eq!(frames, 48);
    assert_eq!(features.len(), 48 * BINS);
    probe(&features, &CAMPPLUS_FEATURES, "campplus_features");
}

/// `snip_edges`: a frame that would run off the end is not taken, and nothing is padded.
///
/// Worth asserting outright because it is the one piece of the analysis with no reference
/// constant behind it -- every number above would be unchanged by a frame count that is one too
/// many, since the probes never reach the end.
#[test]
fn takes_only_the_frames_that_fit() {
    let analysis = Analysis::seamless();

    assert_eq!(analysis.frames(400), 1);
    assert_eq!(analysis.frames(559), 1);
    assert_eq!(analysis.frames(560), 2);
    assert_eq!(analysis.frames(8000), 48);

    // Shorter than one frame is no frames, not a panic and not a padded one.
    assert_eq!(analysis.frames(399), 0);
    assert_eq!(analysis.frames(0), 0);
}

/// The two analyses differ in exactly one field, and it is the scaling.
///
/// This is the claim the module note makes at length; it is cheap to keep it true.
#[test]
fn differs_from_kaldi_only_in_the_scaling() {
    let (seamless, kaldi) = (Analysis::seamless(), Analysis::kaldi());

    assert_eq!(seamless.scale, 32768.0);
    assert_eq!(kaldi.scale, 1.0);

    assert_eq!(seamless.frame_length, kaldi.frame_length);
    assert_eq!(seamless.hop, kaldi.hop);
    assert_eq!(seamless.fft_length, kaldi.fft_length);
    assert_eq!(seamless.bins, kaldi.bins);
    assert_eq!(seamless.low, kaldi.low);
    assert_eq!(seamless.preemphasis, kaldi.preemphasis);
}
