// The reference constants below are machine-written by `tools/s2mel_reference.py` at f32's own
// precision. Trimming each to the shortest decimal that round-trips would make the file disagree
// with what the generator prints, which is the one property worth keeping.
#![allow(clippy::excessive_precision)]

//! S2Mel against S2Mel: this runtime's denoiser beside IndexTTS's own.
//!
//! The constants come from `tools/s2mel_reference.py`, which downloads the reference
//! implementation and runs it. Not a second reading of the paper — such a thing would agree with
//! a bug as readily as with the model.
//!
//! No package and no download at test time. Every parameter is filled from its own name, by the
//! same FNV-1a hash and the same sine in both languages. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/s2mel_reference.py
//! ```
//!
//! The model is small in every width — 16 mel bands, a 64-wide transformer, four heads — and
//! keeps every count: thirteen transformer layers and eight WaveNet layers. Depth is what the
//! U-net skip connections turn on, since half the layers hand one forward to the other half off
//! the end of a list; at a depth of two there is nothing to get wrong and at thirteen there is an
//! off-by-one in three places.

use waifu::flint::{Device, Graph, Ir, ParamSource, RunContext, Tensor, Value};
use waifu::s2mel::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

const IN_CHANNELS: i32 = 16;
const HIDDEN: i32 = 64;
const DEPTH: i32 = 13;
const HEADS: i32 = 4;
const CONTENT_DIM: i32 = 32;
const STYLE_DIM: i32 = 24;
const WAVENET_DIM: i32 = 64;
const FRAMES: i32 = 24;

const TIME: f32 = 0.3;
const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.6;

// Generated by tools/s2mel_reference.py -- 24 frames, 16 bands.

/// `transformer_out`, (1, 24, 64) -- 8 of 1536, at [0, 199, 398, 597, 796, 995, 1194, 1393].
const TRANSFORMER_OUT: [f32; 8] = [
    -9.935895e-01,
    -1.188305e-01,
    7.169707e-01,
    -9.255088e-01,
    1.312920e+00,
    -1.910710e+00,
    1.645545e+00,
    -1.357826e+00,
];

/// `denoised`, (1, 16, 24) -- 8 of 384, at [0, 55, 110, 165, 220, 275, 330, 1].
const DENOISED: [f32; 8] = [
    2.055123e+00,
    1.646545e+00,
    1.431041e+00,
    1.616427e+00,
    -1.189399e+00,
    -1.369040e+00,
    -1.201144e+00,
    2.054988e+00,
];

fn config() -> Config {
    Config {
        in_channels: IN_CHANNELS,
        hidden_dim: HIDDEN,
        depth: DEPTH,
        num_heads: HEADS,
        content_dim: CONTENT_DIM,
        style_dim: STYLE_DIM,
        wavenet_dim: WAVENET_DIM,
        wavenet_layers: 8,
        wavenet_kernel: 5,
        frequency_embedding_size: 256,
    }
}

/// FNV-1a over a parameter's name. The Python side computes the same thing the same way.
fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

/// Every weight, made up from its own name at the moment the graph asks for it.
struct Filled;

impl ParamSource for Filled {
    fn load(&self, name: &str, shape: &[i32]) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(shape, &fill(name, count, WEIGHT_SCALE))?)
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn tensor(name: &str, shape: &[i32]) -> Tensor {
    let count: usize = shape.iter().map(|size| *size as usize).product();

    Tensor::from_f32(shape, &fill(name, count, INPUT_SCALE)).unwrap()
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn close(got: &[f32], want: &[f32], tolerance: f32, what: &str) {
    assert_eq!(got.len(), want.len(), "{what}: lengths differ");

    for (index, (a, b)) in got.iter().zip(want).enumerate() {
        assert!(
            (a - b).abs() <= tolerance * (1.0 + b.abs()),
            "{what} at {index}: {a} is not {b}"
        );
    }
}

/// One step of the trajectory, against the step the reference takes.
#[test]
fn the_denoiser_is_the_reference_denoiser() {
    let config = config();

    let x = tensor("x", &[1, IN_CHANNELS, FRAMES]);
    let prompt_x = tensor("prompt_x", &[1, IN_CHANNELS, FRAMES]);
    let cond = tensor("cond", &[1, FRAMES, CONTENT_DIM]);
    let style = tensor("style", &[1, STYLE_DIM]);

    // The timestep's sinusoid and the rotary tables are the host's, as the model's are.
    let time = s2mel::timestep_embedding(TIME, 256, CPU).unwrap();
    let (cos, sin) = s2mel::rotary_tables(FRAMES, HIDDEN / HEADS, 10000.0, CPU).unwrap();

    let g = Graph::new();
    let out = s2mel::graph(
        &g,
        g.input("x"),
        g.input("prompt_x"),
        g.input("cond"),
        g.input("style"),
        g.input("time"),
        g.input("time"),
        &config,
        FRAMES,
        g.input("cos"),
        g.input("sin"),
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let outputs = Ir::compile(&g)
        .run(
            &RunContext::new(&filled)
                .input("x", &x)
                .input("prompt_x", &prompt_x)
                .input("cond", &cond)
                .input("style", &style)
                .input("time", &time)
                .input("cos", &cos)
                .input("sin", &sin),
        )
        .unwrap();

    let result = outputs[0].1.to_device(CPU).unwrap();
    assert_eq!(result.shape(), vec![1, IN_CHANNELS, FRAMES]);

    let got = result.to_vec_f32().unwrap();
    let indices = probe_indices(got.len(), DENOISED.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    close(&sampled, &DENOISED, 2e-3, "denoised");
}

/// The transformer trunk on its own, so that a failure lands on one side of it or the other.
///
/// This is the half with the skip connections and the rotary convention in it, which are the two
/// things most likely to be subtly wrong while still producing a tensor of the right shape.
#[test]
fn the_transformer_trunk_is_the_reference_trunk() {
    let config = config();

    let x = tensor("x", &[1, IN_CHANNELS, FRAMES]);
    let prompt_x = tensor("prompt_x", &[1, IN_CHANNELS, FRAMES]);
    let cond = tensor("cond", &[1, FRAMES, CONTENT_DIM]);
    let style = tensor("style", &[1, STYLE_DIM]);

    let time = s2mel::timestep_embedding(TIME, 256, CPU).unwrap();
    let (cos, sin) = s2mel::rotary_tables(FRAMES, HIDDEN / HEADS, 10000.0, CPU).unwrap();

    let g = Graph::new();
    let out: Value = s2mel::trunk(
        &g,
        g.input("x"),
        g.input("prompt_x"),
        g.input("cond"),
        g.input("style"),
        g.input("time"),
        &config,
        FRAMES,
        g.input("cos"),
        g.input("sin"),
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let outputs = Ir::compile(&g)
        .run(
            &RunContext::new(&filled)
                .input("x", &x)
                .input("prompt_x", &prompt_x)
                .input("cond", &cond)
                .input("style", &style)
                .input("time", &time)
                .input("cos", &cos)
                .input("sin", &sin),
        )
        .unwrap();

    let result = outputs[0].1.to_device(CPU).unwrap();
    assert_eq!(result.shape(), vec![1, FRAMES, HIDDEN]);

    let got = result.to_vec_f32().unwrap();
    let indices = probe_indices(got.len(), TRANSFORMER_OUT.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    close(&sampled, &TRANSFORMER_OUT, 2e-3, "transformer");
}
