// The reference constants below are machine-written by `tools/s2mel_reference.py` at f32's own
// precision. Trimming each to the shortest decimal that round-trips would make the file disagree
// with what the generator prints, which is the one property worth keeping.
#![allow(clippy::excessive_precision)]

//! S2Mel against S2Mel: this runtime's denoiser beside IndexTTS's own.
//!
//! The constants come from `tools/s2mel_reference.py`, which downloads the reference
//! implementation and runs it. Not a second reading of the paper — such a thing would agree with
//! a bug as readily as with the model.
//!
//! No package and no download at test time. Every parameter is filled from its own name, by the
//! same FNV-1a hash and the same sine in both languages. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/s2mel_reference.py
//! ```
//!
//! The model is small in every width — 16 mel bands, a 64-wide transformer, four heads — and
//! keeps every count: thirteen transformer layers and eight WaveNet layers. Depth is what the
//! U-net skip connections turn on, since half the layers hand one forward to the other half off
//! the end of a list; at a depth of two there is nothing to get wrong and at thirteen there is an
//! off-by-one in three places.

use waifu::flint::{Device, Graph, Ir, ParamSource, Residency, RunContext, Tensor, Value};
use waifu::s2mel::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

const IN_CHANNELS: i32 = 16;
const HIDDEN: i32 = 64;
const DEPTH: i32 = 13;
const HEADS: i32 = 4;
const CONTENT_DIM: i32 = 32;
const STYLE_DIM: i32 = 24;
const WAVENET_DIM: i32 = 64;
const FRAMES: i32 = 24;

const REGULATOR_IN: i32 = 40;
const REGULATOR_CHANNELS: i32 = 32;
const REGULATOR_STAGES: i32 = 4;
const TOKENS: i32 = 9;

const TIME: f32 = 0.3;
const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.6;

// Generated by tools/s2mel_reference.py -- 24 frames, 16 bands.

/// `regulated`, (1, 24, 32) -- 8 of 768, at [0, 103, 206, 309, 412, 515, 618, 721].
const REGULATED: [f32; 8] = [
    6.958275e-01,
    -3.661222e-01,
    -3.045151e-01,
    4.386941e-01,
    -1.432054e-01,
    -7.657101e-01,
    -3.458984e-01,
    8.656241e-01,
];

/// `transformer_out`, (1, 24, 64) -- 8 of 1536, at [0, 199, 398, 597, 796, 995, 1194, 1393].
const TRANSFORMER_OUT: [f32; 8] = [
    -9.935895e-01,
    -1.188305e-01,
    7.169707e-01,
    -9.255088e-01,
    1.312920e+00,
    -1.910710e+00,
    1.645545e+00,
    -1.357826e+00,
];

/// `denoised`, (1, 16, 24) -- 8 of 384, at [0, 55, 110, 165, 220, 275, 330, 1].
const DENOISED: [f32; 8] = [
    2.055123e+00,
    1.646545e+00,
    1.431041e+00,
    1.616427e+00,
    -1.189399e+00,
    -1.369040e+00,
    -1.201144e+00,
    2.054988e+00,
];

fn config() -> Config {
    Config {
        in_channels: IN_CHANNELS,
        hidden_dim: HIDDEN,
        depth: DEPTH,
        num_heads: HEADS,
        content_dim: CONTENT_DIM,
        style_dim: STYLE_DIM,
        wavenet_dim: WAVENET_DIM,
        wavenet_layers: 8,
        wavenet_kernel: 5,
        frequency_embedding_size: 256,
    }
}

/// FNV-1a over a parameter's name. The Python side computes the same thing the same way.
fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

/// Every weight, made up from its own name at the moment the graph asks for it.
struct Filled;

impl ParamSource for Filled {
    fn read(&self, name: &str, shape: &[i32], _pinned: bool) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(shape, &fill(name, count, WEIGHT_SCALE))?)
    }

    /// Made on the host, which is where these tests run.
    fn device(&self) -> Device {
        CPU
    }

    /// Kept: a weight made out of its name costs nothing to keep and there is no package
    /// behind it to stream one out of.
    fn residency(&self) -> Residency {
        Residency::Device
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn tensor(name: &str, shape: &[i32]) -> Tensor {
    let count: usize = shape.iter().map(|size| *size as usize).product();

    Tensor::from_f32(shape, &fill(name, count, INPUT_SCALE)).unwrap()
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

fn close(got: &[f32], want: &[f32], tolerance: f32, what: &str) {
    assert_eq!(got.len(), want.len(), "{what}: lengths differ");

    for (index, (a, b)) in got.iter().zip(want).enumerate() {
        assert!(
            (a - b).abs() <= tolerance * (1.0 + b.abs()),
            "{what} at {index}: {a} is not {b}"
        );
    }
}

/// One step of the trajectory, against the step the reference takes.
#[test]
fn the_denoiser_is_the_reference_denoiser() {
    let config = config();

    let x = tensor("x", &[1, IN_CHANNELS, FRAMES]);
    let prompt_x = tensor("prompt_x", &[1, IN_CHANNELS, FRAMES]);
    let cond = tensor("cond", &[1, FRAMES, CONTENT_DIM]);
    let style = tensor("style", &[1, STYLE_DIM]);

    // The timestep's sinusoid and the rotary tables are the host's, as the model's are.
    let time = s2mel::timestep_embedding(TIME, 256, CPU).unwrap();
    let (cos, sin) = s2mel::rotary_tables(FRAMES, HIDDEN / HEADS, 10000.0, CPU).unwrap();

    let g = Graph::new();
    let out = s2mel::graph(
        &g,
        g.input("x"),
        g.input("prompt_x"),
        g.input("cond"),
        g.input("style"),
        g.input("time"),
        g.input("time"),
        &config,
        FRAMES,
        g.input("cos"),
        g.input("sin"),
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g, Residency::Device);
    let preloaded = ir.load(&filled).unwrap();
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .preloaded(&preloaded)
                .input("x", &x)
                .input("prompt_x", &prompt_x)
                .input("cond", &cond)
                .input("style", &style)
                .input("time", &time)
                .input("cos", &cos)
                .input("sin", &sin),
        )
        .unwrap();

    let result = outputs[0].1.to_device(CPU).unwrap();
    assert_eq!(result.shape(), vec![1, IN_CHANNELS, FRAMES]);

    let got = result.to_vec_f32().unwrap();
    let indices = probe_indices(got.len(), DENOISED.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    close(&sampled, &DENOISED, 2e-3, "denoised");
}

/// The transformer trunk on its own, so that a failure lands on one side of it or the other.
///
/// This is the half with the skip connections and the rotary convention in it, which are the two
/// things most likely to be subtly wrong while still producing a tensor of the right shape.
#[test]
fn the_transformer_trunk_is_the_reference_trunk() {
    let config = config();

    let x = tensor("x", &[1, IN_CHANNELS, FRAMES]);
    let prompt_x = tensor("prompt_x", &[1, IN_CHANNELS, FRAMES]);
    let cond = tensor("cond", &[1, FRAMES, CONTENT_DIM]);
    let style = tensor("style", &[1, STYLE_DIM]);

    let time = s2mel::timestep_embedding(TIME, 256, CPU).unwrap();
    let (cos, sin) = s2mel::rotary_tables(FRAMES, HIDDEN / HEADS, 10000.0, CPU).unwrap();

    let g = Graph::new();
    let out: Value = s2mel::trunk(
        &g,
        g.input("x"),
        g.input("prompt_x"),
        g.input("cond"),
        g.input("style"),
        g.input("time"),
        &config,
        FRAMES,
        g.input("cos"),
        g.input("sin"),
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g, Residency::Device);
    let preloaded = ir.load(&filled).unwrap();
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .preloaded(&preloaded)
                .input("x", &x)
                .input("prompt_x", &prompt_x)
                .input("cond", &cond)
                .input("style", &style)
                .input("time", &time)
                .input("cos", &cos)
                .input("sin", &sin),
        )
        .unwrap();

    let result = outputs[0].1.to_device(CPU).unwrap();
    assert_eq!(result.shape(), vec![1, FRAMES, HIDDEN]);

    let got = result.to_vec_f32().unwrap();
    let indices = probe_indices(got.len(), TRANSFORMER_OUT.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    close(&sampled, &TRANSFORMER_OUT, 2e-3, "transformer");
}

/// The length regulator, which turns one vector per semantic token into one per mel frame.
///
/// Its own test because it is its own module in the reference, and because the resize in the
/// middle of it is the one place a gather had to be written as a matrix — see
/// `nearest_selection`. Nine tokens onto twenty-four frames is deliberately not a whole ratio, so
/// that a resize which only handles integer scaling would be caught.
#[test]
fn the_length_regulator_is_the_reference_regulator() {
    let config = s2mel::RegulatorConfig {
        in_channels: REGULATOR_IN,
        channels: REGULATOR_CHANNELS,
        out_channels: REGULATOR_CHANNELS,
        stages: REGULATOR_STAGES,
    };

    let tokens = tensor("tokens", &[1, TOKENS, REGULATOR_IN]);
    let selection = s2mel::nearest_selection(TOKENS, FRAMES, CPU).unwrap();

    let g = Graph::new();
    let out = s2mel::length_regulator(
        &g,
        g.input("tokens"),
        g.input("selection"),
        &config,
        FRAMES,
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g, Residency::Device);
    let preloaded = ir.load(&filled).unwrap();
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .preloaded(&preloaded)
                .input("tokens", &tokens)
                .input("selection", &selection),
        )
        .unwrap();

    let result = outputs[0].1.to_device(CPU).unwrap();
    assert_eq!(result.shape(), vec![1, FRAMES, REGULATOR_CHANNELS]);

    let got = result.to_vec_f32().unwrap();
    let indices = probe_indices(got.len(), REGULATED.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    close(&sampled, &REGULATED, 2e-3, "regulated");
}

/// `mish` is written without a logarithm; this is that identity, against the definition.
///
/// `x * tanh(softplus(x))` with `softplus(x) = ln(1 + exp(x))`, computed here in f64 straight
/// from the definition, against the exp-only form the graph uses.
#[test]
fn mish_is_the_activation_it_replaces() {
    let values: Vec<f32> = (-40..=40).map(|i| i as f32 * 0.25).collect();
    let x = Tensor::from_f32(&[1, 1, values.len() as i32], &values).unwrap();

    let g = Graph::new();
    let out = s2mel::mish(&g, g.input("x"), F32, CPU).unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g, Residency::Device);
    let preloaded = ir.load(&filled).unwrap();
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .preloaded(&preloaded)
                .input("x", &x),
        )
        .unwrap();
    let got = outputs[0].1.to_device(CPU).unwrap().to_vec_f32().unwrap();

    let want: Vec<f32> = values
        .iter()
        .map(|v| {
            let v = *v as f64;
            (v * (1.0 + v.exp()).ln().tanh()) as f32
        })
        .collect();

    close(&got, &want, 1e-5, "mish");
}

// ---------------------------------------------------------------------------------------------
// the sampler
// ---------------------------------------------------------------------------------------------

/// The Euler solver, against an integral that can be done by hand.
///
/// The network is replaced by a constant velocity field, which makes the whole trajectory exact:
/// `steps` steps of `1 / steps` each add up to one unit of time, so whatever the field says is
/// added exactly once. Checking arithmetic against a closed form rather than against a recorded
/// number is what makes this say the loop is right and not merely unchanged.
#[test]
fn the_solver_integrates_a_constant_velocity_exactly() {
    let channels = 3;
    let frames = 8;
    let prompt_len = 3;

    let z = tensor("z", &[1, channels, frames]);
    let prompt = tensor("prompt", &[1, channels, prompt_len]);
    let velocity: Vec<f32> = (0..channels * frames)
        .map(|i| 0.25 + i as f32 * 0.01)
        .collect();

    for steps in [1, 4, 7] {
        let field = Tensor::from_f32(&[1, channels, frames], &velocity).unwrap();
        let out = s2mel::solve_euler(&z, &prompt, prompt_len, steps, 0.0, |_, _, _, _| {
            Ok(field.clone())
        })
        .unwrap();

        let got = out.to_device(CPU).unwrap().to_vec_f32().unwrap();
        let start = z.to_vec_f32().unwrap();

        for row in 0..channels as usize {
            for frame in 0..frames as usize {
                let index = row * frames as usize + frame;

                // The prompt's own frames are held at zero throughout, never integrated.
                let want = match frame < prompt_len as usize {
                    true => 0.0,
                    false => start[index] + velocity[index],
                };

                assert!(
                    (got[index] - want).abs() < 1e-5,
                    "{steps} steps, row {row} frame {frame}: {} is not {want}",
                    got[index]
                );
            }
        }
    }
}

/// Guidance combines the two passes the way the reference combines them, and asks for the second
/// one only when the rate is above zero.
#[test]
fn guidance_is_two_passes_combined() {
    let (channels, frames, prompt_len) = (2, 6, 2);
    let rate = 0.7f32;

    let z = tensor("z", &[1, channels, frames]);
    let prompt = tensor("prompt", &[1, channels, prompt_len]);

    let conditioned = vec![0.5f32; (channels * frames) as usize];
    let free = vec![0.2f32; (channels * frames) as usize];

    let mut asked = Vec::new();
    let out = s2mel::solve_euler(
        &z,
        &prompt,
        prompt_len,
        1,
        rate,
        |_, prompt_x, _, guided| {
            asked.push(guided);

            // The unguided pass is handed a prompt of zeros; the guided one the real thing.
            let held = prompt_x.to_vec_f32().unwrap();
            let empty = held.iter().all(|value| *value == 0.0);
            assert_eq!(empty, !guided, "the wrong prompt went to the {guided} pass");

            Ok(Tensor::from_f32(
                &[1, channels, frames],
                match guided {
                    true => &conditioned,
                    false => &free,
                },
            )
            .unwrap())
        },
    )
    .unwrap();

    assert_eq!(
        asked,
        vec![true, false],
        "one guided pass then one free one"
    );

    let got = out.to_device(CPU).unwrap().to_vec_f32().unwrap();
    let start = z.to_vec_f32().unwrap();
    let combined = (1.0 + rate) * 0.5 - rate * 0.2;

    for row in 0..channels as usize {
        for frame in prompt_len as usize..frames as usize {
            let index = row * frames as usize + frame;
            let want = start[index] + combined;

            assert!(
                (got[index] - want).abs() < 1e-5,
                "row {row} frame {frame}: {} is not {want}",
                got[index]
            );
        }
    }
}

/// With the rate at zero there is one pass and no second one, which is what makes guidance
/// something you pay for rather than something you always pay for.
#[test]
fn no_guidance_is_one_pass() {
    let (channels, frames) = (2, 4);

    let z = tensor("z", &[1, channels, frames]);
    let prompt = tensor("prompt", &[1, channels, 1]);

    let mut passes = 0;
    let field = Tensor::from_f32(
        &[1, channels, frames],
        &vec![0.1f32; (channels * frames) as usize],
    )
    .unwrap();

    s2mel::solve_euler(&z, &prompt, 1, 3, 0.0, |_, _, _, guided| {
        passes += 1;
        assert!(guided, "an unguided pass was asked for at a rate of zero");

        Ok(field.clone())
    })
    .unwrap();

    assert_eq!(passes, 3, "three steps, one pass each");
}
