// The reference constants below are machine-written by `tools/semantic_codec_reference.py` at
// f32's own precision.
#![allow(clippy::excessive_precision)]

//! The semantic codec against MaskGCT's own, as IndexTTS-2.5 vendors it.
//!
//! `tools/semantic_codec_reference.py` downloads the reference and runs it. No package and no
//! download at test time: every parameter is filled from its own name, by the same FNV-1a hash
//! and the same sine in both languages.
//!
//! Twelve ConvNeXt layers, as shipped, with every width cut — a 32-wide feature instead of 1024,
//! a 64-entry codebook instead of 8192.
//!
//! The search for the nearest codebook entry gets a test of its own rather than resting on the
//! codes this small model happens to pick. With sixty-four entries and made-up weights it picks
//! the same one for every frame, which would pass against almost any indexing mistake; the
//! similarity it picked from is the real check of the encoder, and `nearest` is checked against a
//! matrix whose answer is obvious by construction.

use waifu::flint::{Device, Graph, Ir, ParamSource, RunContext, Tensor};
use waifu::semantic_codec::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

const HIDDEN: i32 = 32;
const CODEBOOK_SIZE: i32 = 64;
const CODEBOOK_DIM: i32 = 8;
const VOCOS_DIM: i32 = 24;
const VOCOS_INTERMEDIATE: i32 = 48;
const VOCOS_LAYERS: i32 = 12;
const FRAMES: i32 = 20;

const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.6;

// Generated by tools/semantic_codec_reference.py -- 20 frames.

/// `similarity`, (1, 10, 64) -- 8 of 640, at [0, 87, 174, 261, 348, 435, 522, 609].
const SIMILARITY: [f32; 8] = [
    -9.881194e-02,
    4.394105e-03,
    9.517793e-02,
    -1.177231e-01,
    1.841616e-01,
    -1.922820e-01,
    1.849453e-01,
    -1.266152e-01,
];

/// `codes`, (1, 10) -- 10 of 10, all.
const CODES: [i32; 10] = [27, 27, 27, 27, 27, 27, 27, 27, 27, 27];

fn config() -> Config {
    Config {
        hidden_size: HIDDEN,
        codebook_size: CODEBOOK_SIZE,
        codebook_dim: CODEBOOK_DIM,
        vocos_dim: VOCOS_DIM,
        vocos_intermediate_dim: VOCOS_INTERMEDIATE,
        vocos_num_layers: VOCOS_LAYERS,
    }
}

fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

struct Filled;

impl ParamSource for Filled {
    fn load(&self, name: &str, shape: &[i32]) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(shape, &fill(name, count, WEIGHT_SCALE))?)
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

/// The encoder end to end, as far as the graph can take it.
fn encode() -> (Vec<i32>, Vec<f32>) {
    let features = Tensor::from_f32(
        &[1, FRAMES, HIDDEN],
        &fill("features", (FRAMES * HIDDEN) as usize, INPUT_SCALE),
    )
    .unwrap();

    let g = Graph::new();
    let out = semantic_codec::similarity(&g, g.input("x"), &config(), FRAMES, F32, CPU).unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g);
    let outputs = ir
        .run(
            &RunContext::new(&filled)
                .input("x", &features),
        )
        .unwrap();

    let tensor = outputs[0].1.to_device(CPU).unwrap();

    (tensor.shape(), tensor.to_vec_f32().unwrap())
}

/// The encoder, against the reference's own.
///
/// This is the real check: twelve ConvNeXt blocks, a stride-two convolution in front of them and
/// a factorized projection behind, all the way to the numbers the token is chosen from.
#[test]
fn the_similarity_is_the_reference_similarity() {
    let (shape, got) = encode();

    // The frame rate is halved on the way in, so twenty frames become ten tokens.
    assert_eq!(shape, vec![1, FRAMES / 2, CODEBOOK_SIZE]);

    let indices = probe_indices(got.len(), SIMILARITY.len());
    let sampled: Vec<f32> = indices.iter().map(|index| got[*index]).collect();

    for (index, (a, b)) in sampled.iter().zip(&SIMILARITY).enumerate() {
        assert!(
            (a - b).abs() <= 2e-3 * (1.0 + b.abs()),
            "similarity at {index}: {a} is not {b}"
        );
    }
}

/// And the tokens that come out of it.
#[test]
fn the_codes_are_the_reference_codes() {
    let (_, got) = encode();
    let codes = semantic_codec::nearest(&got, CODEBOOK_SIZE as usize);

    assert_eq!(codes, CODES);
}

/// `nearest` on a matrix whose answer is obvious, which is what the reference's own codes are too
/// degenerate to establish.
///
/// Three rows with the maximum in three different places, one of them negative throughout so that
/// an implementation starting from zero rather than from the first element is caught, and one
/// with the largest value repeated so that the first of the two wins -- which is what
/// `torch.max` does and therefore what the tokens were chosen by.
#[test]
fn nearest_picks_the_largest_of_each_row() {
    let rows: Vec<f32> = vec![
        // the maximum at the end
        0.1, 0.2, 0.3, 0.9, //
        // the maximum at the start
        0.7, -0.2, 0.3, 0.4, //
        // every value negative, the least negative in the middle
        -0.9, -0.8, -0.1, -0.5, //
        // a tie, which the earlier index takes
        0.4, 0.6, 0.6, 0.2,
    ];

    assert_eq!(semantic_codec::nearest(&rows, 4), vec![3, 0, 2, 1]);
}
