// The reference constants below are machine-written by `tools/w2v_bert_reference.py` at f32's
// own precision.
#![allow(clippy::excessive_precision)]

//! w2v-bert against transformers' own, which is where the reference lives — no download of
//! source or of weights, since `Wav2Vec2BertModel` is in the pinned transformers in the venv.
//!
//! Every parameter is filled from its own name, by the same FNV-1a hash and the same sine in both
//! languages. Regenerate with:
//!
//! ```text
//! .venv/bin/python tools/w2v_bert_reference.py
//! ```
//!
//! Every width is cut, and so is the layer count — four rather than twenty-four — because a
//! conformer stack has no bookkeeping that turns on its depth: layer *n* reads layer *n-1* and
//! that is all. What is kept is the shape of one layer, which is where this model is unusual: two
//! feed forwards added back at half weight, a causal depthwise convolution, and scores carrying a
//! term for how far apart two frames are.
//!
//! Three probes rather than one. IndexTTS reads `hidden_states[17]` out of a twenty-four layer
//! model, so what matters is not only that the stack is right but that stopping partway lands
//! where the reference says it does.

use waifu::flint::{Device, Graph, Ir, ParamSource, Residency, RunContext, Tensor};
use waifu::w2v_bert::{self, Config};
use waifu::Result;

const CPU: Device = Device::Cpu;
const F32: waifu::DType = waifu::DType::Float;

const FEATURE_DIM: i32 = 20;
const HIDDEN: i32 = 32;
const HEADS: i32 = 4;
const INTERMEDIATE: i32 = 64;
const CONV_KERNEL: i32 = 7;
const LEFT_POSITIONS: i32 = 6;
const RIGHT_POSITIONS: i32 = 2;
const LAYERS: i32 = 4;
const PARTIAL: i32 = 2;
const FRAMES: i32 = 14;

const WEIGHT_SCALE: f64 = 0.25;
const INPUT_SCALE: f64 = 0.6;

// Generated by tools/w2v_bert_reference.py -- 14 frames, 4 layers.

/// `projected`, (1, 14, 32) -- 8 of 448, at [0, 63, 126, 189, 252, 315, 378, 441].
const PROJECTED: [f32; 8] = [
    4.367012e-01,
    2.154894e-01,
    -7.624101e-01,
    8.731392e-02,
    4.876143e-01,
    -3.865646e-01,
    4.434645e-01,
    2.871408e-01,
];

/// `partial`, (1, 14, 32) -- 8 of 448, at [0, 63, 126, 189, 252, 315, 378, 441].
const PARTIAL_OUT: [f32; 8] = [
    4.340248e-01,
    1.105302e-01,
    -1.110221e-03,
    -4.072424e-01,
    2.433386e-02,
    8.593803e-03,
    2.449133e-01,
    3.907364e-01,
];

/// `encoded`, (1, 14, 32) -- 8 of 448, at [0, 63, 126, 189, 252, 315, 378, 441].
const ENCODED: [f32; 8] = [
    -2.297134e-01,
    5.465157e-02,
    1.042079e-01,
    6.507190e-01,
    2.856524e-01,
    1.318082e-01,
    -1.094703e-01,
    -4.130524e-01,
];

fn config() -> Config {
    Config {
        feature_dim: FEATURE_DIM,
        hidden_size: HIDDEN,
        num_heads: HEADS,
        intermediate_size: INTERMEDIATE,
        conv_kernel: CONV_KERNEL,
        left_positions: LEFT_POSITIONS,
        right_positions: RIGHT_POSITIONS,
        layer_norm_eps: 1e-5,
    }
}

fn hash32(name: &str) -> u32 {
    let mut value: u32 = 0x811c_9dc5;
    for byte in name.bytes() {
        value = (value ^ u32::from(byte)).wrapping_mul(0x0100_0193);
    }

    value
}

fn fill(name: &str, count: usize, scale: f64) -> Vec<f32> {
    let seed = f64::from(hash32(name) % 10007) * 0.001;

    (0..count)
        .map(|i| ((i as f64 * 0.7371 + seed).sin() * scale) as f32)
        .collect()
}

struct Filled;

impl ParamSource for Filled {
    fn read(&self, name: &str, shape: &[i32], _pinned: bool) -> Result<Tensor> {
        let count: usize = shape.iter().map(|size| *size as usize).product();

        Ok(Tensor::from_f32(shape, &fill(name, count, WEIGHT_SCALE))?)
    }

    /// Made on the host, which is where these tests run.
    fn device(&self) -> Device {
        CPU
    }

    /// Kept: a weight made out of its name costs nothing to keep and there is no package
    /// behind it to stream one out of.
    fn residency(&self) -> Residency {
        Residency::Device
    }

    fn shape_of(&self, _: &str) -> Option<Vec<i32>> {
        None
    }

    fn has(&self, _: &str) -> bool {
        true
    }

    fn check(&self, _: &str, _: &[i32]) -> Result<()> {
        Ok(())
    }
}

fn probe_indices(length: usize, limit: usize) -> Vec<usize> {
    let step = (length / limit).max(1);

    (0..limit).map(|i| (i * step + i * 7) % length).collect()
}

/// Run `layers` of the encoder and sample the result where the reference sampled it.
fn run(layers: i32) -> (Vec<i32>, Vec<f32>) {
    let features = Tensor::from_f32(
        &[1, FRAMES, FEATURE_DIM],
        &fill("features", (FRAMES * FEATURE_DIM) as usize, INPUT_SCALE),
    )
    .unwrap();

    let config = config();
    let distances = w2v_bert::distance_indices(FRAMES, &config, CPU).unwrap();

    let g = Graph::new();
    let out = w2v_bert::graph(
        &g,
        g.input("x"),
        &config,
        FRAMES,
        layers,
        g.input("distances"),
        F32,
        CPU,
    )
    .unwrap();
    g.output("out", out);

    let filled = Filled;
    let ir = Ir::compile(&g, Residency::Device);
    let held = ir.load(&filled).unwrap();
    let outputs = ir
        .run(
            &held,
            &RunContext::new(&filled)
                .input("x", &features)
                .input("distances", &distances),
        )
        .unwrap();

    let tensor = outputs[0].1.to_device(CPU).unwrap();
    let values = tensor.to_vec_f32().unwrap();
    let indices = probe_indices(values.len(), 8);

    (
        tensor.shape(),
        indices.iter().map(|index| values[*index]).collect(),
    )
}

fn close(got: &[f32], want: &[f32], what: &str) {
    for (index, (a, b)) in got.iter().zip(want).enumerate() {
        assert!(
            (a - b).abs() <= 2e-3 * (1.0 + b.abs()),
            "{what} at {index}: {a} is not {b}"
        );
    }
}

/// The feature projection alone, which is `hidden_states[0]`.
#[test]
fn the_projection_is_the_reference_projection() {
    let (shape, got) = run(0);

    assert_eq!(shape, vec![1, FRAMES, HIDDEN]);
    close(&got, &PROJECTED, "projection");
}

/// Stopping partway, which is what IndexTTS does: it reads sixteen layers of twenty-four.
///
/// Its own test because "the stack is right" and "reading it early lands in the right place" are
/// different claims, and only the second is what `hidden_states[17]` depends on.
#[test]
fn stopping_partway_lands_where_the_reference_says() {
    let (shape, got) = run(PARTIAL);

    assert_eq!(shape, vec![1, FRAMES, HIDDEN]);
    close(&got, &PARTIAL_OUT, "two layers");
}

/// And the whole stack.
#[test]
fn the_encoder_is_the_reference_encoder() {
    let (shape, got) = run(LAYERS);

    assert_eq!(shape, vec![1, FRAMES, HIDDEN]);
    close(&got, &ENCODED, "encoder");
}
